### ISSUE TITLE
[Bug]: handler function in default configuration does not use correct parameters

### ISSUE THREAD

**Issue by mcauley-penney** [danilshvalov/org-modern.nvim#1]
First, thanks for the plugin! I was excited to see the PR to Org for this. Also, I realize this is brand-new and that I may have used the tool wrong, so I apologize if the error I discuss below is my fault. 

The handler function given in the README configuration appears to receive a table containing the title and items, not as separate or denested items. See the GIF below. 

In the first part, I use my keybindings (`<leader>oa`) to access Org's menu. Given an error, I check the messages to see the output of the print statement I include, which displays that `title` and `items` are within the first parameter, a table. Changing the parameters to the handler as well as the `open` call, the menu opens correctly. 
 
![modern-menu](https://github.com/danilshvalov/org-modern.nvim/assets/59481467/4fce41f9-c166-43cb-b8a9-3893b6969f12)

**Comment by danilshvalov** [comment]
Hi! I'm very sorry, I was busy implementing virtual indents and completely forgot about the menu. I'll fix it now!

**Comment by danilshvalov** [comment]
Please, try this configuration snippet:

```lua
local Menu = require("org-modern.menu")

require("orgmode").setup({
  ui = {
    menu = {
      handler = function(data)
        Menu:new({
          window = {
            margin = { 1, 0, 1, 0 },
            padding = { 0, 1, 0, 1 },
            title_pos = "center",
            border = "single",
            zindex = 1000,
          },
          icons = {
            separator = "➜",
          },
        }):open(data)
      end,
    },
  },
})
```

**Comment by mcauley-penney** [comment]
That works, thanks! I apologize that I opened this while you were still working on it, btw
