### ISSUE TITLE
Help with the example config

### ISSUE THREAD

**Issue by rgmfn** [danilshvalov/org-modern.nvim#4]
I know I'm just missing something big, but not sure where to find it. I am using the example config given, and I am getting 'org-modern.menu' not found. I haven't worked with lua before (haven't migrated from vimscript), so it's probably not understanding lua.

Also the lua is being called within a lua block in my init.vim, so it is interpreting it as lua.

# Full error:

Error detected while processing /Users/rgmfn/.config/nvim/init.vim:
line  308:
E5108: Error executing lua [string ":lua"]:18: module 'org-modern.menu' not found:
        no field package.preload['org-modern.menu']
        no file './org-modern/menu.lua'
        no file '/opt/homebrew/share/luajit-2.1.0-beta3/org-modern/menu.lua'
        no file '/usr/local/share/lua/5.1/org-modern/menu.lua'
        no file '/usr/local/share/lua/5.1/org-modern/menu/init.lua'
        no file '/opt/homebrew/share/lua/5.1/org-modern/menu.lua'
        no file '/opt/homebrew/share/lua/5.1/org-modern/menu/init.lua'
        no file './org-modern/menu.so'
        no file '/usr/local/lib/lua/5.1/org-modern/menu.so'
        no file '/opt/homebrew/lib/lua/5.1/org-modern/menu.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './org-modern.so'
        no file '/usr/local/lib/lua/5.1/org-modern.so'
        no file '/opt/homebrew/lib/lua/5.1/org-modern.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:18: in main chun

**Comment by danilshvalov** [comment]
Hi! Have you installed `org-modern.nvim`? For example, using [`lazy.nvim`](https://github.com/folke/lazy.nvim) it is done like this:

```lua
require("lazy").setup({
  -- ...
  "danilshvalov/org-modern.nvim",
})
```

**Comment by rgmfn** [comment]
Yeah... can't believe that was it, forgot to actually run the install command even though it was in my rc. Excited to have this! Looks super cool :)
